version: '3'

services:
  dynamodb:
    image: deangiberson/aws-dynamodb-local
    ports:
      - '8000:8000'

  lambda:
    build:
      context: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - '.:/home/ec2user'
    entrypoint: /bin/bash
    command: ["/home/ec2user/scripts/db-setup.sh", "http://dynamodb:8000"]
    tty: true
    depends_on:
      - dynamodb
