service: dynamodb-lambda

plugins:
  - serverless-offline

custom:
  env:
    development:
      DB_TABLE: users-develop
      ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
      REGION: ${env:AWS_REGION}
      DYNAMO_LOCAL_ENDPOINT: ${env:DYNAMO_LOCAL_ENDPOINT}

    staging:
      DB_TABLE: users-staging
      ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
      REGION: ${env:AWS_REGION}

    production:
      DB_TABLE: users
      ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
      SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
      REGION: ${env:AWS_REGION}

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  environment: ${self:custom.env.${opt:stage}}
  timeout: 60

functions:
  users:
    handler: handler.api
    events:
      - http:
          path: users/{email}
          method: get
          cors: '*'
