service: dynamodb-lambda

plugins:
  - serverless-offline

custom:
  env:
    development:
      DB_TABLE: users-develop
      ACCESS_KEY_ID: asd
      SECRET_ACCESS_KEY: asd
      REGION: eu-west-1
      ENDPOINT: http://dynamodb:8000

    staging:
      DB_TABLE: users-staging
      ACCESS_KEY_ID: asd
      SECRET_ACCESS_KEY: asd
      REGION: eu-west-1

    production:
      DB_TABLE: users
      ACCESS_KEY_ID: asd
      SECRET_ACCESS_KEY: asd
      REGION: eu-west-1

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  environment: ${self:custom.env.${opt:stage}}
  timeout: 60

functions:
  api:
    handler: handler.api
    events:
      - http:
          path: api
          method: get
          cors: '*'
